spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: 94411944159
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'